<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cyberPhysical_Incident" nsURI="http://www.example.org/cyberPhysical_Incident"
    nsPrefix="cyberPhysical_Incident">
  <eClassifiers xsi:type="ecore:EClass" name="Activity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="facilitatingConditions"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="certainty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextActivities" upperBound="-1"
        eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousActivities" upperBound="-1"
        eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paths" upperBound="-1"
        eType="#//Path"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initiator" eType="#//ActivityInitiator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accomplices" upperBound="-1"
        eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="victims" upperBound="-1"
        eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetedAssets" upperBound="-1"
        eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="endTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exploitedAssets" upperBound="-1"
        eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ActivityType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behaviourType" eType="#//Behaviour"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precondition" eType="#//Precondition"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="systemAction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postcondition" lowerBound="1"
        eType="#//Postcondition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CrimeScript">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class defines and describes the crime committed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="category" eType="#//ScriptCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scenes" upperBound="-1"
        eType="#//Scene"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goals" upperBound="-1"
        eType="#//Goal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetedAssets" upperBound="-1"
        eType="#//Asset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainLocation" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="victims" upperBound="-1"
        eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="offenders" upperBound="-1"
        eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="higherLevelScriptName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intent" eType="#//Intent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="motive" upperBound="-1"
        eType="#//Motive" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scene">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextScenes" upperBound="-1"
        eType="#//Scene"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previousScenes" upperBound="-1"
        eType="#//Scene"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" upperBound="-1"
        eType="#//Activity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Motive">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class defines the motive for which the crime was committed i.e. why the crime was committed."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="True"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Goal">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class defines the objectives of a crime"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" upperBound="-1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Intent">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class defines the intent of the crime that was comitted i.e. what is the crime that was committed"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Level">
    <eLiterals name="LOW"/>
    <eLiterals name="MEDIUM" value="1"/>
    <eLiterals name="HIGH" value="2"/>
    <eLiterals name="VERY_HIGH" value="3"/>
    <eLiterals name="UNKNOWN" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Asset" eSuperTypes="#//IncidentEntity">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This class defines assets that were targeted by a crime"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vulnerability" upperBound="-1"
        eType="#//Vulnerability" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraints" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity1" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity2" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionProbability"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bidirectional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vulnerabilities" upperBound="-1"
        eType="#//Vulnerability"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//ConnectionState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Location" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Connection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentEntity" eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedEntities" upperBound="-1"
        eType="#//Location"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionsKnowledge" eType="#//Knowledge"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containedAssetsKnowledge"
        eType="#//Knowledge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource" eSuperTypes="#//IncidentEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Path">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activities" upperBound="-1"
        eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityInitiator" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="#//IncidentEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//ActorRole"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="#//ActorLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncidentDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="crimeScript" lowerBound="1"
        eType="#//CrimeScript" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scene" upperBound="-1"
        eType="#//Scene" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="intent" eType="#//Intent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="goal" upperBound="-1" eType="#//Goal"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="motive" upperBound="-1"
        eType="#//Motive" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="asset" upperBound="-1"
        eType="#//Asset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" upperBound="-1"
        eType="#//Resource" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" upperBound="-1"
        eType="#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" upperBound="-1"
        eType="#//Connection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paths" upperBound="-1"
        eType="#//Path" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActivityType">
    <eLiterals name="PHYSICAL" value="1"/>
    <eLiterals name="CYBER" value="3"/>
    <eLiterals name="PHYSICAL_CYBER" value="2"/>
    <eLiterals name="CYBER_PHYSICAL" value="3"/>
    <eLiterals name="UNKNOWN" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vulnerability">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="URL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="severity" eType="#//Level"
        defaultValueLiteral="MEDIUM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Behaviour">
    <eLiterals name="NORMAL"/>
    <eLiterals name="SUSPICIOUS" value="1"/>
    <eLiterals name="MALICIOUS" value="2"/>
    <eLiterals name="UNKNOWN" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstractionLevel" eType="#//AbstractionLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        eType="#//Expression" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" abstract="true" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Expression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" lowerBound="1" eType="#//Expression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contains" abstract="true" eSuperTypes="#//TopologicalRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectedTo" abstract="true" eSuperTypes="#//TopologicalRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Not" abstract="true" eSuperTypes="#//UnaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="namespace" value=""/>
        <details key="group" value="#newAttribute"/>
        <details key="processing" value="strict"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectivity" upperBound="-1"
        eType="#//Connectivity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="site" eType="#//Site" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Precondition" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="TopologicalRelation" abstract="true"
      eSuperTypes="#//BinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Equal" abstract="true" eSuperTypes="#//BinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="Greater" abstract="true" eSuperTypes="#//BinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" abstract="true" eSuperTypes="#//BinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="BigraphExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        upperBound="-1" eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="innername" upperBound="-1"
        eType="#//InnerName" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Or" abstract="true" eSuperTypes="#//BinaryExpression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReachableFrom" abstract="true" eSuperTypes="#//TopologicalRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Near" abstract="true" eSuperTypes="#//TopologicalRelation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Condition" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="1"
        eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="assoicatedConditions" upperBound="-1"
        eType="#//Condition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Postcondition" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="FacilitatingCondition" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Knowledge">
    <eLiterals name="PARTIAL" value="1"/>
    <eLiterals name="EXACT" value="1"/>
    <eLiterals name="UNKNOWN" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScriptCategory">
    <eLiterals name="PATTERN" value="1"/>
    <eLiterals name="PROTOPATTERN" value="2"/>
    <eLiterals name="METAPATTERN" value="3"/>
    <eLiterals name="INSTANCE" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncidentEntity" eSuperTypes="#//ActivityInitiator #//Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mobility" eType="#//Mobility"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connectivity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isClosed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InnerName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isClosed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outername" eType="#//Connectivity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Site">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isClosed" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActorRole">
    <eLiterals name="OFFENDER"/>
    <eLiterals name="ACCOMPLICE" value="1"/>
    <eLiterals name="VICTIM" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActorLevel">
    <eLiterals name="INDIVIDUAL"/>
    <eLiterals name="GROUP" value="1"/>
    <eLiterals name="ORGANISATION" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityPattern">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Severity" eType="#//Level"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="skillsRequired" eType="#//Level"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="patternsFollow" upperBound="-1"
        eType="#//ActivityPattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="abstractActivity" upperBound="-1"
        eType="#//Activity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incidententity" upperBound="-1"
        eType="#//IncidentEntity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" upperBound="-1"
        eType="#//Connection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="likelihood" eType="#//Level"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Mobility">
    <eLiterals name="MOVABLE"/>
    <eLiterals name="FIXED" value="1"/>
    <eLiterals name="UNKNOWN" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AbstractionLevel">
    <eLiterals name="ANYSUBCLASS"/>
    <eLiterals name="EXACT" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConnectionState">
    <eLiterals name="TEMPORARY"/>
    <eLiterals name="PERMANENT" value="1"/>
    <eLiterals name="UNKNOWN" value="2"/>
  </eClassifiers>
</ecore:EPackage>
